language: java
git:
  depth: 1
jdk:
  - openjdk8
dist: trusty
cache:
  directories:
    - $HOME/.m2

deploy:
  provider: bluemixcloudfoundry
  skip_cleanup: true
  username: valentin.duchemin@dauphine.eu
  password: $BLUEMIX_PASSWORD
  organization: valentin.duchemin@dauphine.eu
  space: dev
  region: eu-gb
  on:	
   all_branches: true	
   condition: $TRAVIS_BRANCH =~ ^Valentin #condition: $TRAVIS_BRANCH =~ ^alex|master #si besoin
